# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ringset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('removable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ringshedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ringset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ringapp.Ringset')),
            ],
        ),
        migrations.CreateModel(
            name='Ringtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=32)),
                ('ringset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ringapp.Ringset')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=32)),
            ],
        ),
    ]
