# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ringapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ringset',
            name='removable',
        ),
    ]
