# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 13:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringapp', '0002_remove_ringset_removable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ringset',
            name='ring_length',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='ringshedule',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ringtime',
            name='ring_time',
            field=models.TimeField(blank=True, default=datetime.time),
        ),
    ]
