# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 18:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringapp', '0003_auto_20160130_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterField(
            model_name='ringset',
            name='name',
            field=models.CharField(max_length=32, verbose_name='ringset name'),
        ),
        migrations.AlterField(
            model_name='ringset',
            name='ring_length',
            field=models.IntegerField(default=2, verbose_name='ring length (sec)'),
        ),
        migrations.AlterField(
            model_name='ringtime',
            name='description',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='ringtime',
            name='ring_time',
            field=models.TimeField(default=datetime.time, verbose_name='ring time'),
        ),
    ]
